modLoader = "javafml"
loaderVersion = "[0,)"
license = "Apache-2.0"

[[mods]]
modId = "dryeye"
version = "${mod_version}"
displayName = "DryEye"
description = "Fixes a cruel oversight causing players' eyes to get dry"
logoFile = "assets/dryeye/icon.png"
displayURL = "https://modrinth.com/project/4gxXfaZG"
authors = "Xavier Pedraza"

[[dependencies.dryeye]]
modId = "forge"
mandatory = true
versionRange = "[62,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dryeye]]
modId = "minecraft"
mandatory = true
versionRange = "[26.1,${mc_version}]"
ordering = "NONE"
side = "BOTH"
